### ISSUE TITLE
Bonobo!

### ISSUE THREAD

**Issue by Nbogage** [freebee-game/enable#1167]

**Comment by gdginger** [comment]
bonobo is of course a very common word and has been since 1926. (The name is thought to derive from a misspelling on a shipping crate from the town of Bolobo on the Congo River near the location from which the first bonobo specimens were collected in the 1920s.) Every dictionary defines the word, including the one main Freebee source. But the jerks running this have oddly enough refused to add it despite requests from at least 11 different users over the past 18 months. (I know....OCD...) I suggest the addition every time it shows up...knowing they will never add it, despite accepting words without vowels and words few dictionaries still list. So.....there are better sites to waste your time on.

**Comment by ibara** [comment]
Pull requests are always welcome! That will help speed things along.

**Comment by ibara** [comment]
Whoops, didn't mean to close this.
