### ISSUE TITLE
Please add bonobo (type of ape)

### ISSUE THREAD

**Issue by Mamagelicious** [freebee-game/enable#1169]

**Comment by gdginger** [comment]
bonobo is of course a very common word and has been since 1926. (The name is thought to derive from a misspelling on a shipping crate from the town of Bolobo on the Congo River near the location from which the first bonobo specimens were collected in the 1920s.) Every dictionary defines the word, including the one main Freebee source. But the assholes running this fucking shitshow have oddly enough refused to add it when requested by at least 11 different users over the past 18 months. I suggest the addition every time it shows up...knowing Mr. Head Jackoff won't add it, despite accepting words without vowels and words few dictionaries still list. So fuck this...there are better sites that actually reflect reality.
